### ISSUE TITLE
Creating new file

### ISSUE THREAD

**Issue by cholcombe973** [spacejam/void#1]
This project looks really useful.  However after creating a new file with either cargo run or ./void I can't seem to do anything.  Hitting space shows a choice option but won't let me type anything.  No other key seems to do anything.  What am I doing wrong?

**Comment by cholcombe973** [comment]
I updated to the latest today.  when I hit ctrl+n on a brand new file i get: 
`WARN - Weird Event Key(Ctrl('n'))`

**Comment by cholcombe973** [comment]
Ok so I figured out that just clicking somewhere on the screen and typing creates a node I think.  I've also figured out how to create subnodes in the tree.  Maybe just a README update for: Getting Started would be enough to get people going.

**Comment by spacejam** [comment]
Sorry for the late response, I only just saw there was an issue and I realized I was not watching this repo!

It's a pleasant surprise to see interest in this so quickly! It's super rough at this point but I'm spending a few hours each day making it more usable.

The current version on crates.io should include the C-n create new node functionality. Today's update allows remapping of keys with a specifiable keyfile, which I added a small section to the README on.

I'd recommend doing this for a rough intro (this is the first time I've written about this, and this may be copy+pasted into a tutorial later):
```
# basic node creation
C-n # create new node
type some text to populate it (empty nodes are automatically deleted when unselected)
Tab # create subnode
type some text to populate it
Enter # create sibling node
type text to populate it

# auto-arrange mode and navigation
C-n # create another new node and add text
C-z # set the current view to auto-arrange (this is set per-view)
left/right arrow # jump between subtrees (it's a little clunky, right now, need to refine the search algorithm)

# scopes
make a deep subtree by hitting tab and populating text on children nodes
select the middle of the deep subtree with arrows or the mouse
C-t # collapse subtree
C-w # drill-down view into the collapsed subtree
C-p # arrange new view in a non-overlapping way
C-q # pop-up to previous view

# tasks
create a tree with a node that contains the text `#task`
give it several children, they are implicitly also tasks
give the children different priorities with `#prio=<n>` in their name
C-v # randomly select a subtask based on priority weights
C-a # mark the task as completed, the graph at the top will show the daily completed tasks for the last week
select a node that has some complete children, and some incomplete children
C-h # hide completed children
```

**Comment by cholcombe973** [comment]
Wow thanks!  This is very helpful.  Yeah if you could include that in the
README that would be great :).  I've had the same thing happen to me where
people will PR my repo and I realized I wasn't watching it haha.

**Comment by spacejam** [comment]
Happy to help! I've added a link to a tutorial (mostly copy+pasted from this) at the top of the README. This project is only a few days old but I'm thinking a lot about it, and I'm definitely interested in hearing about anything that you may find confusing / concerning / annoying so I can smooth out the experience. I've been using it pretty frequently even though it's still rudimentary, but that leads me to build up habits around things that are not acceptable workarounds for many people, but to me they've become normalized. It's easy for me to lose a sense of priority for those (although I'm using my local instance as a bugtracker, and I use it to keep track of rough edges I encounter) so I will happily prioritize a fix for issues you have!
