### ISSUE TITLE
clean up dependencies

### ISSUE THREAD

**Issue by iqualfragile** [spacejam/void#4]
as stated earlier, networking should be optional, so hyper and all its dependencies can be made an optional feature
maplit is largely useless, as you can just do vec![(a,b),(c,d),...].into_iter().collect() and get a hashmap.
rust_crypto is a) not secure to use according to the authors, and b) not even used.

**Comment by spacejam** [comment]
I've removed maplit and rust_crypto, I'll think about a nicer way of optionally including hyper.  Hyper is pretty overkill for the usage, and I like your suggestion of GeoClue!
https://github.com/spacejam/void/commit/52ad87dabb254d8d55ad34d288272e232e22df64
